triggers:
- envs: []
  last_enabled_at: 2024-02-07 14:37:01.588235
  name: refresh_green_taxi_data
  pipeline_uuid: green_taxi_etl
  schedule_interval: 0 5 * * *
  schedule_type: time
  settings:
    landing_time_enabled: true
  sla: null
  start_time: 2024-02-07 14:35:00
  status: active
  variables: {}
